책 검색 페이지 구현
6ITAll/book-it-da pull request #36
Opened 2024-12-18 10:43 UTC by Hyunsangs

## 연관 이슈

- #25 

## 작업 요약
- Done 
  - 책 검색 기능
  - UI 제작 ( 검색바, 북 카드, 캐러셀,  페이지네이션 )
  - 베스트셀러 조회 
  
  

## 작업 상세 설명
- 검색 결과에 따라 몇 건인지 확인 가능
- 검색 후 관련도 순, 평점순, 판매량순, 출간일 순으로 정렬 가능
- 검색하지 않았을 때나, 0 건이면 처음엔 검색 결과 없다는 글자로 표시 함 
- 캐러셀 부분 flex로 감싸지거나, width를 %로 주고나서 화면을 줄이면 없어지는 버그가 있었음
  그래서 어쩔 수 없이 px단위로 고정 시킴. 북 카드 부분도 px단위로 적용함.

 추가+ 
- 검색바 밑에 #태그 들은 구현을 하지 못하였음.
이유는 알라딘 open api를 봤을 때 카테고리만 받아오는 api가 존재하지 않음.
그래서 저 부분은,, 어떻게 해야 될지 고민을 해봐야 할 것 같습니다.

### 추가 라이브러리

```jsx
npm install @mui/icons-material
```

```jsx
npm install react-slick slick-carousel
```

```jsx
npm install --save-dev @types/react-slick
```

## 리뷰 요구사항
- (구현 완료시 ) 예상 리뷰 시간 20분~
- 최대한 가독성 좋고, 재사용 가능하게 제작중이긴 하나 많이 미흡할 것 같습니다. 이상하거나 부족한 부분 있으면 말씀해주세요.
- redux-toolkit , rtk-query 처음쓰다보니 어떻게 적절히 사용해야 하는지 잘 모르겠네요 ㅠㅠ
- 공통 컴포넌트 캐러셀 하나 빼두긴 했는데,  bookCard를 아직 완벽하게 재사용 가능하게 코드를 짜진 못한 것 같습니다..
- 동영상으로 첨부해서 확인 해보시면 좋을 것 같습니다.
## Preview 이미지 (필요시)

https://github.com/user-attachments/assets/5ebb85f8-ce73-4314-9c99-9278249d61ee

## 최종 ui 모습
![스크린샷 2024-12-19 오후 5 44 07](https://github.com/user-attachments/assets/e9a9b815-549e-40d7-af59-19172feabc8d)
![스크린샷 2024-12-19 오후 5 45 13](https://github.com/user-attachments/assets/6336faf8-f4b5-498a-8d8d-5d7bd583a876)

2024-12-18 11:23 UTC, publdaze approved these changes
감사합니다! PR 제목은 혼동이 있을 것 같아서 패키지 설치? 정도로 바꿔주면 좋을 것 같습니다!

2024-12-18 11:29 UTC, publdaze commented
> 감사합니다! PR 제목은 혼동이 있을 것 같아서 패키지 설치? 정도로 바꿔주면 좋을 것 같습니다!

아 해당 PR에서 계속 작업 진행하실 예정인가요? 그럼 제목 그대로 두시고 이어서 작업 진행해주시면 됩니다!
- 저는 일단 #37 이 PR 머지된 후 아이콘 활용하여 사용하면 될 것 같습니다!

2024-12-18 13:32 UTC, publdaze requested changes
MUI 아이콘 버전이 머지된 혜정님 PR이랑 달라서 충돌 나는가 봐요! develop pull 받아서 충돌 한 번 해결해줘야 할 것 같습니다! (의존성은 develop 기준으로 맞춰주면 좋을 것 같습니다!)

2024-12-18 15:07 UTC, Hyunsangs commented
develop 브랜치에 맞게 버전 바꾸었습니다!

2024-12-18 23:22 UTC, publdaze requested changes

2024-12-18 23:22 UTC, publdaze commented on src/App.tsx
> +import MyPage from './pages/MainPage/Mypage';
```suggestion
import MyPage from './pages/MyPage/MyPage';
```

이전 상태로 잘 못 돌았간 것 같습니다! 수정 부탁드려요!

2024-12-18 23:43 UTC, publdaze commented on src/components/BookSearchPage/BestBookCard.tsx
> +      </Box>
[MUI의 Card](https://mui.com/material-ui/react-card/#primary-action) 컴포넌트를 활용해봐도 좋을 것 같아요!

`CardActionArea` 컴포넌트 사용 시 링크 기능도 같이 처리 가능한 것 같습니다. ([참고](https://stackoverflow.com/questions/49007357/how-to-make-the-whole-card-component-clickable-in-material-ui-using-react-js))
`hover`에 대한 처리도 별도의 CSS 입힐 필요 없이 컴포넌트에 기본 스타일로 들어가 있어서 코드가 간결해질 것 같아요!
(대신 어느정도 고정된 스타일이 있기 때문에, 원하는 디자인으로 가려면 별도의 커스텀이 있어야 할 수도 있겠네요)

`CardMedia` 컴포넌트로 이미지 처리도 용이할 것 같아요!

2024-12-18 23:43 UTC, publdaze commented on src/components/BookSearchPage/BestBookCard.tsx
> +          `}
MUI에서는 [`sx`](https://mui.com/system/getting-started/the-sx-prop/) 라는 prop을 제공해주기 때문에 별도로 css 호출해서 사용할 필요없이 sx prop으로 재정의할 스타일 넣어주시면 됩니다!

color의 경우도 Typography의 prop로 활용 가능해서 prop으로 넘겨주는 방식으로 처리해도 될 것 같습니다!

그리고 색 적용 시 기본적으로는 아래와 같이 지정된 팔레트 활용하면 좋을 것 같아요! ([참고](https://mui.com/material-ui/customization/palette/#values))
 -> 이후 여러가지 테마를 사용할 수 있도록 확장한다거나, 테마 색을 변경하거나 할 때, 한 번에 교체가 가능해 용이합니다.

<img width="300" alt="image" src="https://github.com/user-attachments/assets/56726bfc-c6cb-45c5-a945-56ea52dbff22" />

만약에 제공되는 기본 팔렛트 외의 색을 사용하고 싶다면, [이 링크](https://mui.com/material-ui/customization/color/#color-palette)를 참고하여 색 지정해주면 어떤 색인지 파악하는 데 용이할 것 같습니다! 저는 아래와 같이 활용하였습니다.

https://github.com/6ITAll/book-it-da/blob/827b350beb6d7cfd5c76038c57d83b092a6f280c/src/components/MyPage/UserInfoSection.tsx#L33

@deenuit113 회색의 경우 자주 사용될 것 같아서 공통된 회색으로 팔레트에 커스텀 해두어도 좋을 것 같아요! 현상님이 사용해주신 #333도 회색 계열인듯 하네요!

(+[Typography에서 활용가능한 Props 참고](https://mui.com/material-ui/api/typography/#props))

2024-12-19 00:18 UTC, publdaze commented on src/components/BookSearchPage/BookCard.tsx
> +      <Stack direction="column" spacing={1} sx={{ mt: 1 }}>
이건 선호도 측면인 것 같아서 반영 안 하셔도 괜찮습니다!

```suggestion
      <Stack direction="column" spacing={1} marginTop={1}>
```

저는 props로 넘길 수 있는 부분은 sx로 스타일 덮어쓰기 보다는 prop으로 넘겨줘서 이 스타일을 사용하겠다고 전달하는 걸 선호하기는 합니다 😊

2024-12-19 00:18 UTC, publdaze commented on src/components/BookSearchPage/BookCard.tsx
> +            </Typography>
저희 서비스가 구매까지 관할하지는 않을 것 같아서 가격은 표시해주지 않아도 될 것 같긴한데, 한 번 논의해보면 좋을 것 같네요.
@Hyunsangs @deenuit113 @ph0109

2024-12-19 00:18 UTC, publdaze commented on src/components/BookSearchPage/BookSearchBar.tsx
> +  };
키보드 처리까지 👍👍

2024-12-19 00:18 UTC, publdaze commented on src/components/BookSearchPage/TagList.tsx
> +  <Stack direction="row" spacing={1} mt={2} flexWrap="wrap">
`marginTop`을 축약형 `mt`로 사용이 가능하군요! 알아갑니다~!

2024-12-19 00:18 UTC, publdaze commented on src/features/BookSearchPage/Slice/bookSearchSlice.ts
> +  sortOption: string; // 정렬 옵션
정렬 옵션은 몇가지로 한정될 것 같아서, string으로 광범위하게 하기보다는 union 타입으로 가능한 것만 명시해두면 좋을 것 같습니다!

ex.
`'SortAccuracy' | 'SortDate' | 'SortPopularity'`

2024-12-19 00:18 UTC, publdaze commented on src/features/BookSearchPage/Slice/bookSearchSlice.ts
> +      state.currentPage = 1; // 새 검색 시 페이지 초기화
이부분 28번 라인에도 공통적으로 사용되고, 물론 주석 처리해주셔서 의미 파악은 가능하지만 코드만으로는 초기화한다는 게 잘 와닿지 않을 수 있을 것 같아서,

```ts
const resetPage = (state: BookSearchState) => {
  state.currentPage = 1;
};
```
이런 식으로 함수 분리해주어도 괜찮을 것 같습니다!

2024-12-19 00:38 UTC, publdaze commented on src/pages/BookSearchPage/BookSearch.tsx
> +    if (inputValue.trim()) {
trim 처리 놓치기 쉬운데, 잘 처리해주셨네요! 👍👍

2024-12-19 00:38 UTC, publdaze commented on src/features/BookSearchPage/Slice/bookSearchSlice.ts
> +  sortOption: string; // 정렬 옵션
const sortOptions = [
    { value: 'SortAccuracy', label: '관련도순' },
    { value: 'CustomerRating', label: '평점순' },
    { value: 'SalesPoint', label: '판매량순' },
    { value: 'PublishTime', label: '출간일순' },
  ];
  
  여기 작성해주신 거 기반으로 유니온 타입으로 묶어주시면 될 것 같네요!

2024-12-19 00:38 UTC, publdaze commented on src/pages/BookSearchPage/BookSearch.tsx
> +              sx={{ color: '#2196f3', mx: 0.5 }}
여기는 `info` 컬러 적용해도 괜찮아보이네요!

2024-12-19 00:38 UTC, publdaze commented on vite.config.ts
> +          rewrite: (path) => path.replace(/^\/api/, ''),
이 부분은 무슨 역할인가요?

2024-12-19 00:38 UTC, publdaze commented on src/store/index.tsx
> +      .concat(bestBookGetApi.middleware), // 미들웨어 추가
```suggestion
      .concat([bookSearchApi.middleware, bestBookGetApi.middleware])
```
이렇게 배열 형태로 작성하면 미들웨어 추가 시 concat 메소드 추가할 필요없이 미들웨어만 추가할 수 있어서 간결할 듯 합니다!

2024-12-19 00:38 UTC, publdaze commented on src/pages/BookSearchPage/BookSearch.tsx
> +              <BookCard
여기 Box로 한 계층 더 감싼 이유가 있나요? 별도의 스타일 처리가 안 되어 있는 것 같아서, 없어도 괜찮다면 중첩구조가 깊어지지 않도록 제거하는 게 좋을 것 같아서요!

2024-12-19 00:39 UTC, Hyunsangs commented on src/App.tsx
> +import MyPage from './pages/MainPage/Mypage';
수정완료했습니다!

2024-12-19 00:50 UTC, deenuit113 commented on src/components/BookSearchPage/BookCard.tsx
> +            </Typography>
> 저희 서비스가 구매까지 관할하지는 않을 것 같아서 가격은 표시해주지 않아도 될 것 같긴한데, 한 번 논의해보면 좋을 것 같네요.
- 알라딘에서 중고책 살 수 있는 매장 정보에 대해서도 제공해주는 것 같습니다! 나중에 기본적인 기능 다 구성하고 나서 고려해보면 좋을 것 같습니다!!

2024-12-19 00:56 UTC, deenuit113 commented on vite.config.ts
> +          rewrite: (path) => path.replace(/^\/api/, ''),
프록시 설정해 주는 부분입니다!
알라딘에서 CORS 헤더를 제공해주지 않아서 기존에 CORS 이슈가 있었는데 해당 설정으로 직접 알라딘 API에 요청하는 것을 우회할 수 있습니다!

2024-12-19 01:01 UTC, deenuit113 commented on vite.config.ts
> +          rewrite: (path) => path.replace(/^\/api/, ''),
클라이언트가 직접 요청을 보내면 http://localhost:3000/~~에서 요청을 보내는 것으로 간주되는데,
프록시 설정하면 Vite 개발 서버에서 origin을 http://www.aladin.co.kr으로 바꾸어 알라딘 API로 요청을 전달해줍니다!

2024-12-19 01:11 UTC, deenuit113 commented on src/components/BookSearchPage/BestBookCard.tsx
> +          `}
-  추가로 배경색이나 폰트 색에 관해서 논의해야 할 것 같습니다! 일반적으로 #ffffff 나 #000000 같은 대비가 강한 색을 쓰지 않아서 이 부분에 대해서 미리 정하고 커스텀 색상으로 추가하는 것이 좋을 것 같습니다.

2024-12-19 01:47 UTC, Hyunsangs commented on src/pages/BookSearchPage/BookSearch.tsx
> +              <BookCard
제거 하도록 하겠습니다..!

2024-12-19 01:47 UTC, Hyunsangs commented on src/store/index.tsx
> +      .concat(bestBookGetApi.middleware), // 미들웨어 추가
감사합니다 ! 수정 하였습니다.

2024-12-19 01:52 UTC, Hyunsangs commented on src/pages/BookSearchPage/BookSearch.tsx
> +              <BookCard
검색 결과로 나온 카드들의 요소마다 제목 저자에 의해 요소들에 크기가 달라져서 Box 태그로 감싸서 커스텀마이징 할 생각입니다.! 이부분도 수정 하겠습니다!

2024-12-19 01:58 UTC, Hyunsangs commented on src/components/BookSearchPage/BestBookCarousel.tsx
> +  const currentWeek = Math.ceil(currentDate.getDate() / 7);
수정 완료 하였습니다!

2024-12-19 03:45 UTC, Hyunsangs commented on vite.config.ts
> +          rewrite: (path) => path.replace(/^\/api/, ''),
`rewrite: (path) => path.replace(/^\/api/, '')`가 없으면,  `/api` ->  baseurl/api/~ 이런식으로 되게 됩니다. 
 원래 요청 url을보면 baseurl/ttb/api/~ 이여서 baseurl을 http://www.aladin.co.kr/ttb/api 이런식으로 해놨습니다.
 `/api` 부분을 `/` 로 해두고 npm run dev 실행해보면 처음부터 baseurl인 aladin 홈페이지로 가지더라고요
 `/`로 하면 클라이언트에서 정적 파일 경로가 잘못 설정되어서, baseURL이 외부 URL(http://www.aladin.co.kr)로 설정되면 정적 파일 요청도 그 외부 URL로 전달하는 것 같습니다.

2024-12-19 04:31 UTC, publdaze commented
#41 해당 PR 머지되어서 develop 풀 받고 경로 반영해줘야 할 듯 합니다!

2024-12-19 08:40 UTC, Hyunsangs commented on src/features/BookSearchPage/Slice/bookSearchSlice.ts
> +  sortOption: string; // 정렬 옵션
수정 완료 하였습니다.

2024-12-19 09:30 UTC, Hyunsangs commented
검색 api에서 최대 한번에 가지고 올 수 있는게 50개 정도이더라고요. 그래서 pagination에서 전체 개수는 가져와서 보여주지만,
페이지네이션에서 14번쯤 부터 누르면 더이상 책이 넘어가지 않습니다.

2024-12-19 09:46 UTC, Hyunsangs commented
절대경로 설정 바꾼거 반영 하였습니다.

2024-12-20 00:47 UTC, publdaze commented on src/components/BookSearchPage/BookCard.tsx
이 컴포넌트는 CommonBookCard로 바뀌면서 이제 사용 안 되는 것 같은데, 파일 지워줘도 괜찮지 않을까 싶네요?~?

2024-12-20 00:47 UTC, publdaze commented on src/components/commons/CommonBookCard.tsx
> +        )}
```suggestion
        {title && (
          <Typography
            variant="body1"
            fontWeight="bold"
            gutterBottom
            sx={{
              overflow: 'hidden',
              textOverflow: 'ellipsis',
              display: '-webkit-box',
              WebkitBoxOrient: 'vertical',
              WebkitLineClamp: 2,
            }}
          >
            {title}
          </Typography>
        )}
        {author && (
          <Typography
            variant="body2"
            sx={{
              color: 'grey.700',
              overflow: 'hidden',
              textOverflow: 'ellipsis',
              display: '-webkit-box',
              WebkitBoxOrient: 'vertical',
              WebkitLineClamp: 1,
            }}
          >
```

디자인 관련이라 반영 안 해주셔도 되는데, 혹시나 더 괜찮아 보인다면 반영해주셔용!
제목이랑 글쓴이가 너무 길어지면 카드도 따라서 너무 길어보이는 것 같아서, 제목은 2줄, 글쓴이는 1줄로 제한해봤습니다! 아래 이미지 참고해주세요!

<img width="892" alt="image" src="https://github.com/user-attachments/assets/8c2579bc-82ad-421c-bee4-69edf592bfce" />

2024-12-20 00:47 UTC, publdaze commented on src/components/commons/CommonBookCard.tsx
> +          objectFit: 'fill', // 이미지를 cover 방식으로 표시
```suggestion
          height: 160, // 고정된 높이
          objectFit: 'contain', // 이미지를 contain 방식으로 표시
```

이것도 디자인 한 번 봐주세용! 만약에 반영 안 하더라도 주석은 수정해야 할 것 같습니다! fill인데, cover로 되어 있어요!

<img width="872" alt="image" src="https://github.com/user-attachments/assets/13fbd89e-f8cc-441d-a896-766e888190b1" />

2024-12-20 02:46 UTC, Hyunsangs commented on src/components/commons/CommonBookCard.tsx
> +        )}
필요없는 컴포넌트 삭제 하겠습니다.
줄임으로 피드백 수정 하겠습니다!

2024-12-20 02:47 UTC, Hyunsangs commented on src/components/commons/CommonBookCard.tsx
> +          objectFit: 'fill', // 이미지를 cover 방식으로 표시
contain이 더 디자인적으로 괜찮은것 같네용

2024-12-20 06:00 UTC, publdaze approved these changes
제가 이것저것 요구사항이 많았는데 열심히 반영해주셔서 감사합니다!
일단 이정도로 머지해도 괜찮을 것 같아보여요!
수고 많으셨습니다!

2024-12-20 06:12 UTC, merged