로그인&회원가입 페이지 구현
6ITAll/book-it-da pull request #43
Opened 2024-12-19 05:28 UTC by ph0109

## 연관 이슈

> 연관된 이슈를 모두 기재 → #[Issue번호] 형식
- #23 
## 작업 요약

> 1~2줄 사이의 요약 설명
- 로그인 및 회원가입 페이지의 기본 구조와 UI 구현
- 사용자 입력 필드, 제출버튼, 기본적 유효성 검사 로직 포함
## 작업 상세 설명

> 주요 기능 및 로직에 대한 설명을 작성
- 사용자 입력 필드(아읻, 비밀번호, 이름, 전화번호) 구현
- 입력값 유효성 검사 로직 추가(필수 입력, 형식 확인)
- 로컬 스토리지를 활용한 임시 회원가입 및 로그인 처리
- 페이지 간 라우팅 설정
## 리뷰 요구사항

> 리뷰 예상 시간 및 집중 리뷰 부분
- 사용자 인증 로직을 지금은 로컬 스토리지를 사용하고 있지만 나중에 서버 연동한다면 보안 필요할 것 같습니다 
- 컴포넌트 구조가 괜찮은지 봐주세요..
## Preview 이미지 (필요시)
회원가입 
<img width="1497" alt="스크린샷 2024-12-19 오후 2 26 19" src="https://github.com/user-attachments/assets/93121bca-90be-4eb3-896d-516e15c5baec" />

아이이디 저장 된 로그인 화면

https://github.com/user-attachments/assets/68ac598a-4e9e-4e65-a42a-151becc56d81

새로 들어왔을 때 아이디가 그대로 있는 걸 확인할 수 있습니다.

2024-12-19 07:01 UTC, publdaze requested changes
MUI 처음 써보시는 거 맞나요? 너무 활용 잘하신 것 같습니다! 👍

files changed 탭 확인해보면 eslint 관련해서 룰에 맞지 않는 부분에 린터 오류 띄워주고 있을 거에요! 이것도 반영 부탁드려요!

그리고 자동 반영이 되어야 하는데 안 된 부분도 있는 것 같아보여서, prettier와 eslint vscode 확장 프로그램 설치되어 있는 지 확인 부탁드려요!

2024-12-19 07:24 UTC, ph0109 commented on src/components/LoginSignup/Login.tsx
> +        <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', mb: 2 }}>
반영해서 코드 수정하도록 하겠습니다 ! 또 하나 알아갑니다 ~

2024-12-19 07:26 UTC, ph0109 commented on src/components/LoginSignup/Login.tsx
> +        <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', mb: 2 }}>
> files changed 탭 확인해보면 eslint 관련해서 룰에 맞지 않는 부분에 린터 오류 띄워주고 있을 거에요! 이것도 반영 부탁드려요!
그리고 자동 반영이 되어야 하는데 안 된 부분도 있는 것 같아보여서, prettier와 eslint vscode 확장 프로그램 설치되어 있는 지 확인 부탁드려요!

문제가 뭔지 모르겠어서 찾아보고 있었는데 이거였네요..! 감사합니다 덕분에 시간 절약됐어요:-)

2024-12-19 08:11 UTC, ph0109 commented
> files changed 탭 확인해보면 eslint 관련해서 룰에 맞지 않는 부분에 린터 오류 띄워주고 있을 거에요! 이것도 반영 부탁드려요!

오류 모두 수정하였습니다. 피드백도 모두 반영하여 코드 수정했습니답!!

2024-12-19 08:45 UTC, publdaze commented on src/components/LoginSignup/Signup.tsx
> +    <Container maxWidth="sm" sx={{ mt: -30 }}>
여기 `sx={{ mt: -30 }}` 이렇게 마진 올려주신 게 로그인이랑 높이 맞추려고 하신게 맞을까요?

맞다면 이렇게 처리하는 것보다 [src/pages/LoginSignup/SignupPage.tsx](https://github.com/6ITAll/book-it-da/pull/43/files#diff-383e7d0aa0bf514607a8a00d29233d24d463540592b2459b34c4b2d95953ca26), [src/pages/LoginSignup/LoginPage.tsx](https://github.com/6ITAll/book-it-da/pull/43/files#diff-40da5dbd4404851b366af06c6ca028cc15f29be5a47183357253c6f7f170b24a) 이 두 군데의 상위 래퍼를 동일하게 맞춰주는 게 좋아보입니다!

```jsx
      sx={{
        height: '100vh',
        justifyContent: 'center',
        alignItems: 'center',
      }}
```

이 스타일이 한 군데만 적용되어 있어서 서로 차이가 발생하는 것 같아요! 제 생각에는 해당 스타일 없애줘도 괜찮아보입니다!

2024-12-19 08:45 UTC, publdaze commented on src/components/LoginSignup/Login.tsx
> +            loginMessage.includes('올바르지 않습니다') ? 'error' : 'primary'
'올바르지 않습니다'라는 텍스트로 에러인지 여부를 판단하기 보다는 `loginMessage` state를 객체로 관리해서 isError 속성을 같이 관리하는 게 어떨까요?

그래서 `loginMessage.isError`로 조건 처리할 수 있도록요! (실제 메시지는 `loginMessage.content`로 관리하거나 해도 될 것 같구요! 네이밍은 원하시는 대로 해주시면 됩니다!)

텍스트가 포함되는 지 여부로만 판단하기에는 `사용자 정보가 없습니다. 회원가입 후 로그인 해주세요.`와 같이 '올바르지 않습니다'가 포함되지 않음에도 에러로 판단되지 않을 수 있을 것 같습니다!

2024-12-19 08:45 UTC, publdaze commented on src/pages/LoginSignup/LoginPage.tsx
음.. 저는 pages 폴더 해당 파일에서 페이지 UI에 대한 컴포넌트를 작성하고, 하위에 분할할 수 있는 컴포넌트들이 `@components` 폴더로 분류되어 가져와 쓸 수 있도록 하는 구조로 생각을 하긴했는데, 혹시 페이지 전체 UI를 따로 컴포넌트로 빼주신 이유가 있나요?

2024-12-20 06:35 UTC, ph0109 commented on src/components/LoginSignup/Signup.tsx
> +    <Container maxWidth="sm" sx={{ mt: -30 }}>
아 그쪽을 수정하는거군요..! 알려주셔서 감사합니다!

2024-12-20 06:40 UTC, ph0109 commented on src/pages/LoginSignup/LoginPage.tsx
로그인이랑 회원가입은 다른 주요 기능이랑 별개로 독립적인 페이지로 생각했어요 !

2024-12-20 07:36 UTC, ph0109 commented on src/components/LoginSignup/Login.tsx
> +            loginMessage.includes('올바르지 않습니다') ? 'error' : 'primary'
수정하였습니당 ! 알려주셔서 감사합니다👍

2024-12-20 07:37 UTC, Hyunsangs commented on src/pages/LoginSignup/LoginPage.tsx
로그인이랑 회원가입은 독립적인 페이지니까 
```
pages
  LoginSignup 폴더 
     LoginPage.tsx
     SignupPage.tsx 
```

```
 pages 
   LoginPage
     LoginPage.tsx
   SignupPage
     SignupPage.tsx 
```
로 바꾸는게 어떤지 생각합니다!

기존대로 원하신다면

```
pages
  LoginSignupPage 폴더 
     LoginPage.tsx
     SignupPage.tsx 
```
Page를 뒤에 붙여주면 좋을 것 같습니다👍🏻
다른 분들도 pages에 바로 하위폴더는 끝에 Page를 붙이고 있어서 
바꾸시면 더 통일성이 있을 것 같습니다.

그리고 
components밑에
  LoginSignup 폴더도 Page를 붙여주시면 좋을 것 같아요!

2024-12-20 11:05 UTC, ph0109 commented on src/pages/LoginSignup/LoginPage.tsx
```
pages
  LoginSignupPage 폴더 
     LoginPage.tsx
     SignupPage.tsx 
```
이 구조로 수정하고 components도 같이 수정해 올렸습니다 !

2024-12-23 08:38 UTC, publdaze approved these changes
수고 많으셨습니다! 👏👏

코멘트 먼저 확인 후 머지 부탁드려요! 일단 먼저 approve 해두고 가보겠습니다!

+제가 yup 부분은 잘 몰라서 yup 활용 부분에서 다른 분 리뷰 한 번 더 받아봐도 좋을 것 같아요!

2024-12-23 08:38 UTC, publdaze commented on src/pages/LoginSignupPage/LoginPage.tsx
> +    </div>
```suggestion
    <Login onLogin={handleLogin} />
```

따로 의미가 없다면 태그 중첩 안 해주고, 컴포넌트로만 구성해도 될 것 같아보이네용?

2024-12-23 08:38 UTC, publdaze commented on src/pages/LoginSignupPage/SignupPage.tsx
> +    </Stack>
```suggestion
    <Signup />
```

여기도 불필요하다면 태그 중첩 없애줘도 될 것 같아보입니다!

2024-12-23 08:38 UTC, publdaze commented on src/components/LoginSignupPage/Signup.tsx
> +    alert('회원가입에 성공했습니다!');
나중에 스낵바로 토스트메시지 공통 컴포넌트로 제작 후 alert 대신 토스트메시지로 바꿔주면 좋을 것 같습니다!

2024-12-26 08:07 UTC, merged